# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: pt

# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
pipeline:
  - name: "SpacyNLP"
    model: "pt_core_news_lg"
    case_sensitive: False
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "SklearnIntentClassifier"
  - name: "FallbackClassifier"
    threshold: 0.5
  - name: "RegexEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    entity_recognition: False
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

  
policies:
  - name: AugmentedMemoizationPolicy
    max_history: 5
    epochs: 300
  - name: RulePolicy
